services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  server:
    build:
      context: ..
    depends_on:
      - kafka
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      SALT: ${SALT}
      MONGO_1_DB_NAME: ${MONGO_1_DB_NAME}
      MONGO_1_HOST: ${MONGO_1_HOST}
      MONGO_1_PORT: ${MONGO_1_PORT}
      MONGO_1_USER: ${MONGO_1_USER}
      MONGO_1_PASS: ${MONGO_1_PASS}
      RABBITMQ_1_USER: ${RABBITMQ_1_USER}
      RABBITMQ_1_PASSWORD: ${RABBITMQ_1_USER}
      RABBITMQ_1_PORT: ${RABBITMQ_1_PORT}
      RABBITMQ_1_HOST: ${RABBITMQ_1_HOST}
    ports:
      - 9999:9999
